---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeflow
  namespace: ${releaseNamespace}
spec:
  interval: 5s
  ref:
    tag: v1.6.1
  timeout: 20s
  url: https://github.com/kubeflow/manifests
