---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow
  namespace: ${releaseNamespace}
spec:
  patches:
  - patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
     - op: add
       path: /metadata/namespace
       value: default
    target:
      kind: ConfigMap
      name: default-install-config.*
  interval: 6h
  path: ./example
  prune: true
  serviceAccountName: ${releaseNamespace}
  sourceRef:
   kind: GitRepository
   name: kubeflow
   namespace: ${releaseNamespace}
